version: 2
build:
  image: latest
submodules:
  include:
    - Font-Awesome
python:
  version: 3
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
  system_packages: true
formats:
  - htmlzip
